apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: k8s-live
  namespace: argocd
spec:
  destination:
    namespace: sre
    server: https://kubernetes.default.svc
  project: default

  sources:
    - path: applications
      repoURL: https://github.com/carioca-org/k8s-live
      targetRevision: HEAD

    - path: namespaces
      repoURL: https://github.com/carioca-org/k8s-live
      targetRevision: HEAD

  syncPolicy:
    automated:
      prune: true
      allowEmpty: true

