apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: k8s-live
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: sre
    server: https://kubernetes.default.svc
  project: default
  source:
    path: .
    repoURL: https://github.com/carioca-org/k8s-live
    targetRevision: HEAD
